# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: lde-koni <lde-koni@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2023/10/03 12:39:54 by lde-koni      #+#    #+#                  #
#    Updated: 2023/10/03 12:54:31 by lde-koni      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC = 







norminette
norminette -R CheckForbiddenSourceHeader